server {
    listen 80;
    server_name 158.160.176.150 foodgram.by www.foodgram.by;
    client_max_body_size 20M;

    # Разрешаем nginx перезагружать DNS для upstream
    resolver 127.0.0.11 valid=30s;

    location /api/ {
        set $backend_upstream backend:8000;
        proxy_pass http://$backend_upstream/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
        set $backend_upstream backend:8000;
        proxy_pass http://$backend_upstream/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /media/ {
        alias /var/html/media/;
    }

    location /static/admin/ {
        alias /var/html/static/admin/;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}